"""add_dynamic_data_jsonb

Revision ID: 38b8b0492e63
Revises: 871fd8d0a3d4
Create Date: 2026-02-22 00:32:31.120302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38b8b0492e63'
down_revision: Union[str, Sequence[str], None] = '871fd8d0a3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('dynamic_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('suppliers', sa.Column('dynamic_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'dynamic_data')
    op.drop_column('products', 'dynamic_data')
    # ### end Alembic commands ###
